import React, { useRef, useState } from 'react';
import { X, Download, Share2, Loader2 } from 'lucide-react';
import html2canvas from 'html2canvas';

interface ShareCardProps {
  isOpen: boolean;
  onClose: () => void;
  imageUrl: string;
  poem: string;
  keyword: string;
}

const ShareCard: React.FC<ShareCardProps> = ({ isOpen, onClose, imageUrl, poem, keyword }) => {
  const captureRef = useRef<HTMLDivElement>(null);
  const [isDownloading, setIsDownloading] = useState(false);

  if (!isOpen) return null;

  const handleDownload = async () => {
    if (!captureRef.current) return;
    setIsDownloading(true);

    try {
        // Wait for images to load just in case, though usually they are ready by the time user clicks
        const canvas = await html2canvas(captureRef.current, {
            backgroundColor: '#0a0a0a', // Force dark background
            scale: 2, // Higher quality
            useCORS: true, // Essential for cross-origin images
            logging: false,
            allowTaint: true,
        });

        const link = document.createElement('a');
        link.download = `TimePoem-${keyword.replace(/\s+/g, '-')}-${Date.now()}.png`;
        link.href = canvas.toDataURL('image/png');
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
    } catch (error) {
        console.error("Failed to generate image:", error);
        alert("Could not generate image. Please try again.");
    } finally {
        setIsDownloading(false);
    }
  };

  const handleNativeShare = async () => {
    if (navigator.share) {
        try {
            await navigator.share({
                title: `Time Poem: ${keyword}`,
                text: poem,
                url: window.location.href
            });
        } catch (err) {
            console.log("Share cancelled");
        }
    } else {
        // Fallback: Copy poem to clipboard
        navigator.clipboard.writeText(`${keyword}\n\n${poem}\n\nGenerated by Time Poem`).then(() => {
            alert("Poem copied to clipboard!");
        });
    }
  };

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-black/90 backdrop-blur-sm animate-fade-in">
      <div className="relative w-full max-w-md bg-[#0a0a0a] border border-purple-500/30 rounded-xl shadow-[0_0_50px_rgba(168,85,247,0.2)] overflow-hidden flex flex-col">
        
        {/* Close Button - Outside of capture area */}
        <button 
            onClick={onClose}
            className="absolute top-3 right-3 z-20 p-2 bg-black/50 rounded-full text-white hover:bg-white/20 transition-colors"
        >
            <X className="w-5 h-5" />
        </button>

        {/* Card Content - THIS IS CAPTURED */}
        <div ref={captureRef} className="bg-[#0a0a0a] relative">
             {/* Image Section */}
            <div className="relative aspect-square w-full overflow-hidden">
                 {/* We add a slight overlay in the capture to ensure text readability if we want, 
                     but here we just rely on the image content */}
                 <img 
                    src={imageUrl} 
                    alt="Time Poem Art" 
                    className="w-full h-full object-cover"
                    crossOrigin="anonymous"
                 />
                 <div className="absolute bottom-0 left-0 right-0 h-32 bg-gradient-to-t from-[#0a0a0a] to-transparent"></div>
            </div>

            {/* Text Section */}
            <div className="p-8 text-center -mt-12 relative z-10">
                {/* Replaced bg-clip-text with solid color + drop-shadow for html2canvas compatibility */}
                <h2 className="font-magic text-3xl text-purple-200 mb-6 tracking-widest uppercase drop-shadow-[0_0_8px_rgba(233,213,255,0.5)]">
                    {keyword}
                </h2>
                
                <div className="font-poetic text-lg text-gray-200 leading-loose mb-8 whitespace-pre-line italic drop-shadow-sm">
                    {poem}
                </div>

                <div className="flex items-center justify-center gap-2 pb-4">
                     <div className="h-[1px] w-10 bg-gradient-to-r from-transparent to-purple-500/50"></div>
                     <span className="text-[10px] text-purple-400/60 tracking-[0.3em] font-magic uppercase">Time Poem</span>
                     <div className="h-[1px] w-10 bg-gradient-to-l from-transparent to-purple-500/50"></div>
                </div>
            </div>
        </div>

        {/* Footer Actions - Outside of capture area */}
        <div className="bg-white/5 p-4 flex gap-3 border-t border-white/5 z-20">
            <button 
                onClick={handleNativeShare}
                className="flex-1 flex items-center justify-center gap-2 py-3 bg-white/10 hover:bg-white/20 text-white rounded-lg transition-all font-medium text-sm"
            >
                <Share2 className="w-4 h-4" /> 分享 (Share)
            </button>
            
            <button 
                onClick={handleDownload}
                disabled={isDownloading}
                className="flex-1 flex items-center justify-center gap-2 py-3 bg-purple-600 hover:bg-purple-500 text-white rounded-lg transition-all font-medium text-sm disabled:opacity-50 disabled:cursor-wait"
            >
                {isDownloading ? (
                    <>
                        <Loader2 className="w-4 h-4 animate-spin" /> 保存中...
                    </>
                ) : (
                    <>
                        <Download className="w-4 h-4" /> 保存图片 (Save)
                    </>
                )}
            </button>
        </div>
      </div>
    </div>
  );
};

export default ShareCard;